
from docopt import docopt


DOCTEXT = f"""
Usage:
  create_platja_models.py --model_name=<mn> --json_path=<jp> --csv_path=<cp> --masks_path=<mp> --output_path=<op>
  create_platja_models.py -h | --help

Options:
  -h --help                             Show this screen.
  --model_name=<mn>                     Str. Name of the file that will represent the beach.
  --json_path=<jp>                      Str. Path to the list of images file generated by "create_list.py correspondances".
  --csv_path=<cp>                       Str. Path to the csv file generated by "create_list.py correspondances".
  --masks_path=<mp>                     Str. Path to the folder where the previous list of images have anotations with the same name but ".segments.pkl" extension.
  --output_path=<op>                    Str. Path where the model will be stored.

"""


def parse_args(argv):

    opts = docopt(DOCTEXT, argv=argv[1:], help=True, version=None, options_first=False)

    model_name = opts['--model_name']
    json_path = opts['--json_path']
    csv_path = opts['--csv_path']
    masks_path = opts['--masks_path']
    output_path = opts['--output_path']

    return model_name, json_path, csv_path, masks_path, output_path
